### ISSUE TITLE
Add an optional sqlite adapter for the cache plugin

### ISSUE THREAD

**Issue by avdg** [avdg/phergie#3]
Work is being done in the branch change/CacheStorage

See https://github.com/avdg/phergie/commits/change%2FCacheStorage

**Comment by avdg** [comment]
Current task: implement the sqlite part using the db plugin

**Comment by Ttech** [comment]
We could implement a Cache Simple and a Cache Smart? Add for now a simple cache method that would work similar to the final method but just make it have a peristaltic cache for the time being?

**Comment by avdg** [comment]
I am just interested in 1 caching solution for the time being, we can optimize or making it more flexible later. Only if that class would be too big, I maybe would consider splitting up the caching class.

But why is this class a plugin, while it doesn't really do something interesting as plugin on its own? Should we move this component to the so called "library"?

**Comment by Ttech** [comment]
I almost got a rough basic setup working.

**Comment by avdg** [comment]
Current tasks:
- integrate the sqlite backend in the core of the cache plugin
- testing

**Comment by avdg** [comment]
I wonder why I discover now that the cache plugin is relying on the global strategy (all keys from all plugins are stored in 1 cache instance). Seems I am having a big lack of good explanations of things...

Lets rewind and make things simpler ;-)
